package it.polimi.ingsw.board.windowpattern;

public enum Restriction {
	FIRST_DICE_RESTRICTION,
	MUST_HAVE_NEAR_DICE_RESTRICTION,
	NEAR_DICE_VALUE_RESTRICTION,
	NEAR_DICE_COLOR_RESTRICTION,
	CELL_VALUE_RESTRICTION,
	CELL_COLOR_RESTRICTION
}
